# These are supported funding model platforms
github: [shayanb]

# Buy Me a Coffee
buy_me_a_coffee: pangana

# Crypto addresses (add to README/landing page)
BTC: bc1qkfq3hg5kpzgy7muc8m3pmh6zemhv820a0ndqgg
ETH: 0xB4D06BDb0C2f1D81E0b0b805Ed813F4ffe960aE2
ZEC: u1pclheucppc87qlffh9m8wjfw87w2nka40w9nxjuqnyppj0kx9xp7z9rg6wx556662y5f8dtfyeynmm2lnz5aqvaqzmnpajlq0mnmkntdqzqqegk8lwv09cnudf3ttzm3878p3030j3lwupj257rmmv9p3ea32hgwsuf3jdh8ycv7q587
Tron: TBSCbnTZCELrMnioobZMkah5r9qS6B1tC6
