#!/bin/bash
# MasterDNS advanced DNS tunnel configuration functions (MahsaNG v16 component)
#
# MasterDnsVPN (github.com/masterking32/MasterDnsVPN) is an advanced DNS tunnel
# optimised beyond dnstt/Slipstream: low-overhead ARQ, resolver load-balancing,
# and high packet-loss stability. Bundled in MahsaNG v16 (MasterDNS v2026.05.10).
#
# Server egress is routed through sing-box's mixed inbound (sing-box:1080),
# matching how dnstt/Slipstream forward traffic in MoaV.

MASTERDNS_CONFIG_DIR="/configs/masterdns"

# DATA_ENCRYPTION_METHOD: 5 = AES-256-GCM (strongest). The MasterDnsVPN server
# expects the key file to be a hex string whose *character* length equals the
# required key length: 16 (AES-128) / 24 (AES-192) / 32 (everything else).
# For method 5 the required length is 32 chars -> openssl rand -hex 16.
MASTERDNS_ENC_METHOD="${MASTERDNS_ENC_METHOD:-5}"

_masterdns_key_chars() {
    case "$1" in
        3) echo 16 ;;  # AES-128-GCM
        4) echo 24 ;;  # AES-192-GCM
        *) echo 32 ;;  # NONE/XOR/ChaCha20/AES-256-GCM
    esac
}

generate_masterdns_config() {
    log_info "Setting up MasterDNS configuration..."

    ensure_dir "$MASTERDNS_CONFIG_DIR"
    ensure_dir "$STATE_DIR/keys"

    local key_file="$STATE_DIR/keys/masterdns-encrypt.key"
    local key_chars
    key_chars=$(_masterdns_key_chars "$MASTERDNS_ENC_METHOD")

    # Generate / validate the symmetric encryption key (stable across re-bootstraps).
    local need_keygen=false
    if [[ ! -s "$key_file" ]]; then
        need_keygen=true
    else
        local cur
        cur=$(tr -d '\n\r ' < "$key_file")
        if [[ ${#cur} -ne $key_chars ]]; then
            log_info "MasterDNS key length ${#cur} != expected ${key_chars} (enc method changed); regenerating"
            need_keygen=true
        fi
    fi

    if [[ "$need_keygen" == "true" ]]; then
        log_info "Generating MasterDNS encryption key (${key_chars} hex chars, method ${MASTERDNS_ENC_METHOD})"
        # openssl rand -hex N emits 2N hex chars; request half the char count.
        # No chmod: state key files follow the repo convention (dnstt/Slipstream)
        # so the unprivileged `moav` user in the service container can read them.
        openssl rand -hex $(( (key_chars + 1) / 2 )) | cut -c1-"${key_chars}" | tr -d '\n' > "$key_file"
    fi

    if [[ ! -s "$key_file" ]]; then
        log_error "MasterDNS encryption key file is empty or missing"
        return 1
    fi

    local md_domain="${MASTERDNS_SUBDOMAIN:-m}.${DOMAIN}"

    # Minimal-but-complete server config. Unspecified tuning knobs are
    # smart-sized internally by the server. Egress is forced through
    # sing-box's mixed SOCKS inbound for parity with dnstt/Slipstream.
    cat > "$MASTERDNS_CONFIG_DIR/server_config.toml" <<EOF
# MasterDnsVPN server configuration (generated by MoaV bootstrap)
# Do not edit by hand — regenerated on every bootstrap.

# --- Tunnel policy -----------------------------------------------------------
DOMAIN = ["${md_domain}"]
PROTOCOL_TYPE = "SOCKS5"
SUPPORTED_UPLOAD_COMPRESSION_TYPES = [0, 1, 2, 3]
SUPPORTED_DOWNLOAD_COMPRESSION_TYPES = [0, 1, 2, 3]

# --- UDP listener ------------------------------------------------------------
UDP_HOST = "0.0.0.0"
UDP_PORT = 5355

# --- DNS-over-tunnel upstream ------------------------------------------------
DNS_UPSTREAM_SERVERS = ["1.1.1.1:53", "1.0.0.1:53"]
DNS_UPSTREAM_TIMEOUT = 4.0

# --- Upstream SOCKS / forwarding ---------------------------------------------
# Route all tunnelled SOCKS connections through sing-box's mixed inbound,
# so MasterDNS egress matches the rest of the MoaV stack.
USE_EXTERNAL_SOCKS5 = true
SOCKS5_AUTH = false
FORWARD_IP = "sing-box"
FORWARD_PORT = 1080
SOCKS_CONNECT_TIMEOUT = 60.0

# --- Security ----------------------------------------------------------------
DATA_ENCRYPTION_METHOD = ${MASTERDNS_ENC_METHOD}
ENCRYPTION_KEY_FILE = "${key_file}"

# --- Logging -----------------------------------------------------------------
LOG_LEVEL = "INFO"
EOF

    # Publish the public connection params (key is required by the client).
    echo "$md_domain" > "$MASTERDNS_CONFIG_DIR/server.domain"
    ensure_dir "/outputs/masterdns"
    cp "$key_file" "/outputs/masterdns/encrypt_key.txt" 2>/dev/null || true
    echo "$md_domain" > "/outputs/masterdns/server.domain"

    log_info "MasterDNS configuration created"
    log_info "Domain: $md_domain  (enc method ${MASTERDNS_ENC_METHOD} / AES-256-GCM)"
}

# Generate MasterDNS client instructions for a user
masterdns_generate_client_instructions() {
    local user_id="$1"
    local output_dir="$2"

    local md_domain="${MASTERDNS_SUBDOMAIN:-m}.${DOMAIN}"
    local key_file="$STATE_DIR/keys/masterdns-encrypt.key"
    local md_key="KEY_NOT_GENERATED"
    [[ -s "$key_file" ]] && md_key=$(tr -d '\n\r ' < "$key_file")

    cat > "$output_dir/masterdns-instructions.txt" <<EOF
# MasterDNS Tunnel Instructions
# =============================
# Advanced DNS tunnel (low-overhead ARQ + resolver load-balancing).
# Faster and more loss-tolerant than dnstt; bundled in MahsaNG v16.
# Use when other methods are blocked — DNS tunnels work when little else does.
#
# Project: https://github.com/masterking32/MasterDnsVPN
# Bundled in: MahsaNG (https://github.com/GFW-knocker/MahsaNG)

# Tunnel Domain:
$md_domain

# Data encryption method (must match server):
$MASTERDNS_ENC_METHOD   # 5 = AES-256-GCM

# Encryption key (keep secret — anyone with this key can use the tunnel):
$md_key

# -------------------------
# Option A: MahsaNG (Android) — easiest
# -------------------------
# 1. Install MahsaNG v16+ from https://github.com/GFW-knocker/MahsaNG/releases
# 2. Add a MasterDNS config with the domain, encryption method and key above.

# -------------------------
# Option B: MasterDnsVPN standalone client
# -------------------------
# Download the client for your OS from:
#   https://github.com/masterking32/MasterDnsVPN/releases
#
# Minimal client_config.toml:
#   DOMAINS = ["$md_domain"]
#   DATA_ENCRYPTION_METHOD = $MASTERDNS_ENC_METHOD
#   ENCRYPTION_KEY = "$md_key"
#   PROTOCOL_TYPE = "SOCKS5"
#   LISTEN_IP = "127.0.0.1"
#   LISTEN_PORT = 18000
#
# Run the client, then point your apps at SOCKS5 127.0.0.1:18000.
# The client also needs a resolver list (client_resolvers) — use the sample
# bundled with the client and/or public resolvers (1.1.1.1:53, 8.8.8.8:53).

# -------------------------
# Notes:
# -------------------------
# - DNS tunneling is slow by design but extremely hard to block.
# - Faster and more stable under packet loss than dnstt/Slipstream.
# - Traffic exits through the MoaV server (your IP appears as the server IP).
# - The NS record for $md_domain must delegate to this server (see docs/DNS.md).
EOF

    log_info "Generated MasterDNS instructions for $user_id"
}
