#!/bin/sh
set -e

# =============================================================================
# dnstt server entrypoint
# =============================================================================

# Log with timestamp (MM-DD HH:MM:SS - SERVICE - MESSAGE)
log() {
    echo "$(date '+%m-%d %H:%M:%S') - dnstt - $*"
}

# Source config file if it exists (generated by bootstrap)
if [ -f /etc/dnstt/server.conf ]; then
    log "Loading config from /etc/dnstt/server.conf"
    . /etc/dnstt/server.conf
fi

# Environment variables override config file, with fallbacks
DNSTT_DOMAIN="${DNSTT_DOMAIN:-t.example.com}"
DNSTT_LISTEN="${DNSTT_LISTEN:-:5353}"
DNSTT_UPSTREAM="${DNSTT_UPSTREAM:-127.0.0.1:8080}"

log " Starting dnstt-server"
log " Domain: $DNSTT_DOMAIN"
log " Listen: $DNSTT_LISTEN"
log " Upstream: $DNSTT_UPSTREAM"

# Look for key file in multiple formats (for backwards compatibility)
KEY_HEX="/state/keys/dnstt-server.key.hex"
KEY_B64="/state/keys/dnstt-server.key.b64"

log " Looking for key files..."
ls -la /state/keys/ 2>&1 || log " /state/keys directory does not exist"

# Wait for any key file to appear
timeout=60
elapsed=0
while [ ! -f "$KEY_HEX" ] && [ ! -f "$KEY_B64" ]; do
    log " Waiting for key file..."
    sleep 2
    elapsed=$((elapsed + 2))
    if [ $elapsed -ge $timeout ]; then
        log " ERROR: No key file found after ${timeout}s. Run bootstrap first."
        log " Expected: $KEY_HEX or $KEY_B64"
        ls -la /state/keys/ 2>&1 || true
        exit 1
    fi
done

# Load key - prefer hex, fall back to base64 and convert
if [ -f "$KEY_HEX" ]; then
    log " Using hex key file: $KEY_HEX"
    PRIVKEY=$(cat "$KEY_HEX" | tr -d '\n\r ')
elif [ -f "$KEY_B64" ]; then
    log " Using base64 key file: $KEY_B64 (converting to hex)"
    # Convert base64 to hex
    PRIVKEY=$(cat "$KEY_B64" | base64 -d | od -A n -t x1 | tr -d ' \n')
else
    log " ERROR: No valid key file found"
    exit 1
fi

log " Private key loaded (${#PRIVKEY} chars)"

# Validate key length (should be 64 hex chars = 32 bytes)
if [ ${#PRIVKEY} -ne 64 ]; then
    log " WARNING: Key length is ${#PRIVKEY}, expected 64 hex chars"
fi

exec dnstt-server -udp "$DNSTT_LISTEN" -privkey "$PRIVKEY" "$DNSTT_DOMAIN" "$DNSTT_UPSTREAM"
