#!/bin/bash
set -euo pipefail

# =============================================================================
# MasterDNS server entrypoint
# Advanced DNS tunnel (ARQ + resolver load-balancing) — MahsaNG v16 component.
# =============================================================================

echo "================================================"
echo "  MoaV MasterDNS (advanced DNS tunnel)"
echo "================================================"

ENABLE_MASTERDNS="${ENABLE_MASTERDNS:-true}"

# MasterDNS is enabled by default. When explicitly disabled, idle quietly
# instead of crash-looping
# (the service is part of the dnstunnel/all profiles for parity with dnstt).
if [[ "$ENABLE_MASTERDNS" != "true" ]]; then
    echo "[masterdns] ENABLE_MASTERDNS is not 'true' — MasterDNS disabled, idling."
    echo "[masterdns] Set ENABLE_MASTERDNS=true in .env to activate."
    # Portable idle (busybox sleep has no 'infinity'); keep the container up.
    while true; do sleep 3600; done
fi

CONFIG_FILE="/etc/masterdns/server_config.toml"
KEY_FILE="/state/keys/masterdns-encrypt.key"

# Wait for the config + key generated by bootstrap.
echo "[masterdns] Looking for server config and encryption key..."
timeout=60
elapsed=0
while [[ ! -f "$CONFIG_FILE" ]] || [[ ! -s "$KEY_FILE" ]]; do
    echo "[masterdns] Waiting for $CONFIG_FILE and $KEY_FILE ..."
    sleep 2
    elapsed=$((elapsed + 2))
    if [[ $elapsed -ge $timeout ]]; then
        echo "[masterdns] ERROR: config/key not found after ${timeout}s. Run bootstrap first."
        echo "[masterdns] Expected: $CONFIG_FILE and $KEY_FILE"
        ls -la /etc/masterdns/ /state/keys/ 2>&1 || true
        exit 1
    fi
done

echo "[masterdns] Config: $CONFIG_FILE"
echo "[masterdns] Encryption key: $KEY_FILE ($(wc -c < "$KEY_FILE" | tr -d ' ') chars)"
echo "================================================"

exec masterdnsvpn -config "$CONFIG_FILE" -nowait
